sources:
  - name: DelegateRegistry
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/manboy-eth/delegate-registry-v2-{context.chainName:goerli}

additionalTypeDefs: |
  extend type Context {
    chainName: String
  }
  extend type Query {
    crossContext(contextId: ID!, chainNames: [String!]!): [Context!]!
    crossContexts(chainNames: [String!]!): [Context!]!
  }

additionalResolvers:
  - ./resolvers.ts

documents:
  - './lib/services/the-graph/queries/**/*.graphql'

codegen:
  contextType: 'MeshContext & { chainName: string, DelegateRegistry: any }'